<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "cinema_session".
 *
 * @property int $id
 * @property int $cinema_id
 * @property string $time_start
 * @property string $time_end
 * @property string $cinema_hall_id
 */
class CinemaSession extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'cinema_session';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['cinema_id', 'cinema_hall_id', 'time_start', 'time_end'], 'required'],
            [['cinema_id', 'cinema_hall_id'], 'integer'],
            [['time_start', 'time_end'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cinema_id' => 'Cinema ID',
            'time_start' => 'Time Start',
            'time_end' => 'Time End',
            'cinema_sessioncol' => 'Cinema Sessioncol',
        ];
    }

    public function beforeSave($insert)
    {
        if (!self::validateDate($this->time_start)){
            return false;
        }

        if (!self::validateDate($this->time_end)){
            return false;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    private static function validateDate($date, $format = 'Y-m-d H:i:s')
    {
        $d = \DateTime::createFromFormat($format, $date);
        // The Y ( 4 digits year ) returns TRUE for any integer with any number of digits so changing the comparison from == to === fixes the issue.
        return $d && $d->format($format) === $date;
    }

    public function getFilm()
    {
        return $this->hasOne(Cinema::className(), ['id' => 'cinema_id']);
    }

    public function getHall()
    {
        return $this->hasOne(CinemaHall::className(), ['id' => 'cinema_hall_id']);
    }
}
